; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.41"

; Modules
projects[admin_menu][version] = "3.0-rc5"

projects[auto_nodetitle][version] = "1.0"

projects[ctools][version] = "1.9"

projects[date][version] = "2.9"

projects[diff][version] = "3.2"

projects[ds][version] = "2.11"

projects[entity][version] = "1.6"

projects[entity_translation][version] = "1.0-beta4"

projects[features][version] = "2.7"

projects[field_group][version] = "1.4"

projects[geolocation][version] = "1.6"

projects[i18n][version] = "1.13"

projects[imagemagick][version] = "1.0"

projects[libraries][version] = "2.2"

projects[link][version] = "1.3"

projects[nodeformcols][version] = "1.0"

projects[references][version] = "2.1"

projects[pathauto][version] = "1.3"

projects[services][version] = "3.12"

projects[strongarm][version] = "2.0"

projects[token][version] = "1.6"

projects[transliteration][version] = "3.2"

projects[unique_field][version] = "1.0-rc1"

projects[uuid][version] = "1.0-beta1"

projects[variable][version] = "2.5"

projects[views][version] = "3.12"

projects[views_datasource][version] = "1.0-alpha2"

projects[mongodb][version] = "1.0-rc2"

; Themes
projects[rubik][version] = "4.3"

projects[tao][version] = "3.1"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[dlts_viewer][download][type] = "git"
projects[dlts_viewer][download][url] = "https://github.com/NYULibraries/dlts_viewer.git"
projects[dlts_viewer][download][branch] = "master"
projects[dlts_viewer][type] = "module"

; Libraries

libraries[Mobile_Detect][download][type] = "git"
libraries[Mobile_Detect][download][url] = "https://github.com/serbanghita/Mobile-Detect.git"
libraries[Mobile_Detect][directory_name] = "Mobile_Detect"
libraries[Mobile_Detect][type] = "library"

libraries[simplehtmldom][download][type] = "get"
libraries[simplehtmldom][download][url] = "http://downloads.sourceforge.net/project/simplehtmldom/simplehtmldom/1.5/simplehtmldom_1_5.zip"
libraries[simplehtmldom][directory_name] = "simplehtmldom"
libraries[simplehtmldom][type] = "library"

libraries[openlayers][download][type] = "git"
libraries[openlayers][download][url] = "https://github.com/openlayers/openlayers.git"
libraries[openlayers][directory_name] = "openlayers"
libraries[openlayers][type] = "library"
